-- SQL BASIC 문제풀이

-- 1번
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

-- 2번
SELECT DEPARTMENT_NAME || '의 정원은 '|| CAPACITY||'명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT;

-- 3번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y' 
AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME ='국어국문학과')
AND SUBSTR(STUDENT_SSN, INSTR(STUDENT_SSN, '-')+1,1) = '2';

-- 4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513079' OR STUDENT_NO = 'A513090' OR STUDENT_NO = 'A513091' OR STUDENT_NO = 'A513110' OR STUDENT_NO = 'A513119'
ORDER BY STUDENT_NAME DESC;

-- 5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9번
SELECT  DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT 
WHERE SUBSTR(STUDENT_NO,1,2)='A2'
AND SUBSTR(STUDENT_ADDRESS,1,2)='전주'
AND ABSENCE_YN ='N';


-- SQL FUNCTION

-- 1번
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번
SELECT PROFESSOR_NAME 교수이름, SUBSTR(TO_CHAR(SYSDATE, 'YYDDMM'),1,2)+2000 - SUBSTR(PROFESSOR_SSN,1,2)-1900 나이
FROM TB_PROFESSOR
ORDER BY PROFESSOR_SSN DESC;

SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - SUBSTR(STUDENT_SSN,1,2)-1900 != 19;

SELECT TO_CHAR(SYSDATE, 'DAY')
FROM DUAL;




